### ISSUE TITLE
CSS appears to be missing

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaClimate/www.juliaclimate.org#1]
My local preview looks fine, but the deployed version seems to be missing styling: https://juliaclimate.org any ideas what I missed? 

CC @tlienart

**Comment by tlienart** [comment]
I'm assuming from Slack that this is fixed?

**Comment by logankilpatrick** [comment]
Yes! Thank you. 

Best, 
Logan Kilpatrick

**Comment by Balinus** [comment]
Thanks for the community website! :) @logankilpatrick @tlienart
